# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# os
os:
  - linux

# Set the python version to 3.6, 3.7
python:
  - "3.6"
  - "3.7"
  - "3.8"

# Install the pip dependency
install:
  - pip install sentencepiece
  - pip install gensim==4.0.1
  - pip install nltk
  - pip install numpy
  - pip install scipy
  - pip install sklearn-crfsuite
  - pip install wasabi

# Run the unit test
script:
  - python test.py
  # - coverage run tests.py
